# 1. Data Importion

In [2]:
import pandas as pd
import numpy as np
import operator
import pickle
import re
from tqdm import tqdm

In [3]:
df_true = pd.read_csv('.\DataSet\True.csv',sep=',')
df_fake = pd.read_csv('.\DataSet\Fake.csv',sep=',')

In [4]:
df_true

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"
...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017"
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017"
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017"
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017"
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017"

In [5]:
df_fake

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"
...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016"
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016"
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016"
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016"
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016"

# 2.Data Cleaning for subject, date
## 2.1.form new column as classifier
### (1) form a new column named as label as classifer
### (2) concatenate df_true & df_fake as df_all

In [6]:
# True is 1, Fake is 0
df_true['label'] = 1
df_fake['label'] = 0

In [7]:
# concat 2 dataframes
df_all = pd.concat([df_true,df_fake])

In [8]:
df_all

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1
...,...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",0
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",0
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",0
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",0
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",0

In [9]:
# reset index
df_all = df_all.reset_index()
df_all = df_all.drop(columns=['index'])

In [10]:
df_all

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1
...,...,...,...,...,...
44893,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",0
44894,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",0
44895,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",0
44896,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",0
44897,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",0

## 2.2. Categorical Data "Subject"

In [11]:
subject_list = df_all['subject'].unique()
subject_list

array(['politicsNews', 'worldnews', 'News', 'politics', 'Government News',
       'left-news', 'US_News', 'Middle-east'], dtype=object)

In [12]:
# turn the subject into 1 hot encoding, make it from norminal category into binary vector
df_subject= pd.get_dummies(df_all.subject,prefix = 'subject')
df_all=df_all.drop(columns=['subject'])
df_subject

,subject_Government News,subject_Middle-east,subject_News,subject_US_News,subject_left-news,subject_politics,subject_politicsNews,subject_worldnews
0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,1,0
3,0,0,0,0,0,0,1,0
4,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...
44893,0,1,0,0,0,0,0,0
44894,0,1,0,0,0,0,0,0
44895,0,1,0,0,0,0,0,0
44896,0,1,0,0,0,0,0,0
44897,0,1,0,0,0,0,0,0

## 2.2. Turn date into year, month, day 3 columns

In [13]:
date = df_all['date'].iloc[1]
print(date)
type(date)

December 29, 2017

str

In [14]:

def formDataFrame(dictData):
    # form df from dict
    df = pd.DataFrame.from_dict(dictData)
    return df

In [15]:
from datetime import date

In [16]:
"""
Turning Date into new 5 attributes: year, month, day, weekday, aprilfool
note: aprilfool -> 1: it's on April Fools' Day, 0: it's not on April Fools' Day, 2: not sure
"""
def turnDate(array):
    dictMon = {
        'January':1,'Jan':1,
        'February':2,'Feb':2,
        'March':3,'Mar':3,
        'April':4,'Apr':4,
        'May':5,
        'June':6,'Jun':6,
        'July':7,'Jul':7,
        'August':8,'Aug':8,
        'September':9,'Sep':9,
        'October':10,'Oct':10,
        'November':11,'Nov':11,
        'December':12,'Dec':12
        }
    dictDate = dict()
    dictDate['year']=list()
    dictDate['month'] = list()
    dictDate['day'] = list()
    dictDate['weekday']=list()
    dictDate['aprilfool']=list()
    for each in tqdm(array):
        matchObj = re.match(r'([a-zA-Z]+) ([0-9]+), ([0-9]+)',each,flags=re.I)
        if matchObj is not None:
            recordedDate = date(int(matchObj.group(3)),int(dictMon[matchObj.group(1)]),int(matchObj.group(2)))
            dictDate['year'].append(recordedDate.year)
            dictDate['month'].append(recordedDate.month)
            dictDate['day'].append(recordedDate.day)
            dictDate['weekday'].append(recordedDate.weekday())
            if recordedDate.month == 4 and recordedDate.day == 1:
                dictDate['aprilfool'].append('yes')
            elif (recordedDate.month == 3 and recordedDate.day >=24) or (recordedDate.month == 4 and recordedDate.day <=8):
                dictDate['aprilfool'].append('close')
            else:
                dictDate['aprilfool'].append('no')
        else:
            dictDate['year'].append(0)
            dictDate['month'].append(0)
            dictDate['day'].append(0)
            dictDate['weekday'].append(0)
            dictDate['aprilfool'].append('not sure')
    
    return dictDate

In [17]:
dictDate = turnDate(df_all['date'])
df_all = df_all.drop(columns=['date'])
df_date = formDataFrame(dictDate)

100%|████████████████████████████████████████████████████████████████████████| 44898/44898 [00:00<00:00, 314748.93it/s]

In [18]:
df_date

       year  month  day  weekday aprilfool
0      2017     12   31        6        no
1      2017     12   29        4        no
2      2017     12   31        6        no
3      2017     12   30        5        no
4      2017     12   29        4        no
...     ...    ...  ...      ...       ...
44893  2016      1   16        5        no
44894  2016      1   16        5        no
44895  2016      1   15        4        no
44896  2016      1   14        3        no
44897  2016      1   12        1        no

[44898 rows x 5 columns]

In [19]:
df_april= pd.get_dummies(df_date.aprilfool,prefix = 'aprilfool')
df_date = df_date.drop(columns=['aprilfool'])

In [20]:
df_april

       aprilfool_close  aprilfool_no  aprilfool_not sure  aprilfool_yes
0                    0             1                   0              0
1                    0             1                   0              0
2                    0             1                   0              0
3                    0             1                   0              0
4                    0             1                   0              0
...                ...           ...                 ...            ...
44893                0             1                   0              0
44894                0             1                   0              0
44895                0             1                   0              0
44896                0             1                   0              0
44897                0             1                   0              0

[44898 rows x 4 columns]

In [21]:
df_date = pd.merge(df_date, df_april, left_index=True, right_index=True)

In [22]:
df_date

,year,month,day,weekday,aprilfool_close,aprilfool_no,aprilfool_not sure,aprilfool_yes
0,2017,12,31,6,0,1,0,0
1,2017,12,29,4,0,1,0,0
2,2017,12,31,6,0,1,0,0
3,2017,12,30,5,0,1,0,0
4,2017,12,29,4,0,1,0,0
...,...,...,...,...,...,...,...,...
44893,2016,1,16,5,0,1,0,0
44894,2016,1,16,5,0,1,0,0
44895,2016,1,15,4,0,1,0,0
44896,2016,1,14,3,0,1,0,0
44897,2016,1,12,1,0,1,0,0

# 3.Data Cleaning for Text Part

In [23]:
# get the array from dataframe fot text cleaning
array_text = list(df_all['text'])
array_title = list(df_all['title'])

In [24]:
# lower the words, separate sepcial symbol, remove punctuation, remove stopwords, then it's done.
# afterwards, use GloVe vectorize the text into vectors, add the other and build together as a long vector.
# finally put those data into model, run it, done. if needed sample it again.

## 3.1. lower the words, insert space into adhered combination of words and punctuations
### Since after lower and insertion of space, the coverage of words in GloVe has rised to 99.14%, and the rest words are mostly special names or messy code, it's ok now to use the data for further analysis.

In [25]:
# becuase GloVe can also represent punctuations as vector, I take punctuation as important part of determining the meaning of text
# thus I didn't choose to remove the punctuations, instead I chose to insert space into the adhered combinations of words and punctuations
# such as "$30", "play for fun, "
def lowerAinsertSpace(array):
    length = len(array)
    for i in tqdm(range(length)):
        # 1st: lower the word
        array[i]=array[i].lower()
        
        # 2nd: insert space between punctuations

        # (1) add space between normal punctuation and word
        array[i] = re.sub(r'[\'a-zA-Z0-9]+',r' \g<0> ',array[i]).strip()
        # (2) add space making word such as 'i'm' to 'i 'm'
        array[i] = re.sub(r'([a-zA-Z]+)(\'[a-zA-Z])+',r'\g<1> \g<2>',array[i]).strip()
        # (3) add space between multiple punctuations
        array[i] = re.sub(r'([^a-zA-Z\'0-9])([^\'a-zA-Z0-9])',r' \g<1> \g<2> ',array[i]).strip()
        # (4) add space between combination of words and numbers
        array[i] = re.sub(r'([\'a-zA-Z])([0-9])',r'\g<1> \g<2>',array[i]).strip()
        array[i] = re.sub(r'([0-9])([\'a-zA-Z])',r'\g<1> \g<2>',array[i]).strip()
        # (5) remove the redundant space
        array[i] = re.sub(r' +',r' ',array[i])
        
    return array

In [26]:
array_text2 = lowerAinsertSpace(array_text)

100%|███████████████████████████████████████████████████████████████████████████| 44898/44898 [01:07<00:00, 668.02it/s]

In [27]:
array_title2 = lowerAinsertSpace(array_title)

100%|█████████████████████████████████████████████████████████████████████████| 44898/44898 [00:02<00:00, 16867.99it/s]

# 4. Check the percentage of words in data can be processed by GloVe pre-trained Data

In [28]:
# import GloVe pre-trained DataSet
# link for downloading the pre-trained GloVe DataSet: https://nlp.stanford.edu/projects/glove/
# import processed words list from glove
GloVe_path=".\DataSet\glove.840B.300d_words.pkl"
def open_pkl(path):
    pickle_file = open(path,mode='rb')
    data = pickle.load(pickle_file)
    pickle_file.close()

    return data

def form_dict(words_list):
    words_dict = dict()
    content="just for data check"
    for word in words_list:
        words_dict[word]=content
    
    return words_dict

In [29]:
glo_words=open_pkl(GloVe_path)
glo_dict = form_dict(glo_words)# because process dict is much faster than processing list

In [30]:
glo_dict["it's"]

'just for data check'

In [31]:
glo_dict["$"]

'just for data check'

In [32]:
glo_dict["0"]

'just for data check'

In [33]:
glo_dict["'m"]

'just for data check'

In [34]:
"""
1. check the distinct words number;
2. check the coverage of GloVe on the dataset;
"""

class CheckCovered:
    def __init__(self,embedding_source):
        self.embedding_source = embedding_source
    
    def distinctWords(self,text_array):
        # gain the distinct words as dict
        vocab = dict()
        for each in tqdm(text_array):
            words_list = each.split(sep=" ")
            for word in words_list:
                if word == '':
                    continue
                try:
                    vocab[word] +=1
                except KeyError:
                    vocab[word] = 1
        return vocab
    
    def checkCoverage(self, text_array):
        # in order to get the coverage of GloVe on the text of DataSet
        vocab = self.distinctWords(text_array)
        cov_vocab =0
        num_vocab = len(vocab)# gain the number of distinct words in all text
        cov_text = 0
        not_cov = dict()
        not_text = 0
        for word in tqdm(vocab.keys()):
            try:
                x = self.embedding_source[word]
                cov_vocab += 1
                cov_text += vocab[word]
            except:
                not_cov[word]=vocab[word]
                not_text += vocab[word]
                pass
        percent_cov_vocab = cov_vocab/num_vocab
        percent_cov_text = cov_text/(cov_text+not_text)
        print("the number of distinct vocabulary of data is {a}".format(a=len(vocab)))
        print("In Embedding Index we have {:.2%} coverage of distinct vocabulary".format(percent_cov_vocab))
        print("And we have {:.2%} coverage of all text".format(percent_cov_text))
        sorted_not_cov = sorted(not_cov.items(),key= operator.itemgetter(1),reverse = True)
        print("The number of words which are not covered in GloVe resource is: {0}".format(len(sorted_not_cov)))
        return sorted_not_cov

In [35]:
cc = CheckCovered(glo_dict)

In [36]:
cc.checkCoverage(array_text)

100%|██████████████████████████████████████████████████████████████████████████| 44898/44898 [00:05<00:00, 8600.77it/s]
100%|█████████████████████████████████████████████████████████████████████| 118935/118935 [00:00<00:00, 1074345.01it/s]

the number of distinct vocabulary of data is 118935
In Embedding Index we have 61.26% coverage of distinct vocabulary
And we have 99.14% coverage of all text
The number of words which are not covered in GloVe resource is: 46076

[('\xa0', 5173),
 ('realdonaldtrump', 4627),
 ('tillerson', 2783),
 ('brexit', 2147),
 ('rohingya', 2055),
 ('manafort', 1235),
 ("'t", 1002),
 ('mnuchin', 980),
 ('gorsuch', 965),
 ('rakhine', 897),
 ('priebus', 872),
 ('duterte', 868),
 ('raqqa', 694),
 ('puigdemont', 645),
 ('filessupport', 594),
 ('jinping', 567),
 ('kellyanne', 553),
 ('abedin', 542),
 ('lavrov', 511),
 ('scaramucci', 504),
 ('reince', 482),
 ('somodevilla', 466),
 ('rosenstein', 447),
 ('chaffetz', 413),
 ('mnangagwa', 403),
 ('mulvaney', 391),
 ('henningsen', 390),
 ('blasio', 384),
 ('houthis', 384),
 ('finicum', 361),
 ('gulen', 354),
 ('houthi', 351),
 ('peskov', 350),
 ('juncker', 347),
 ('scalise', 340),
 ('tmsnrt', 338),
 ('kuczynski', 338),
 ('kislyak', 338),
 ('cfpb', 334),
 ('rouhani', 325),
 ('rauner', 323),
 ('ramaphosa', 288),
 ('barzani', 286),
 ('barnier', 284),
 ('angerer', 281),
 ('idlib', 276),
 ('hillaryclinton', 271),
 ('veselnitskaya', 269),
 ('yellen', 263),
 ('macri', 263),
 ('zinke', 261),
 ('marawi', 255),
 ('guterres', 252),
 ('nusra', 238),
 ('seanhannity', 235),
 ('guccifer', 223),
 ('yiannopoulos', 223),
 ('zarrab', 217),
 ('sokha', 217),
 ('isil', 217),
 ('daesh', 214),
 ('puzder', 211),
 ('nauert', 209),
 ('raedle', 200),
 ('cernovich', 194),
 ('curiel', 191),
 ('mcmullin', 186),
 ('ossoff', 184),
 ('bharara', 178),
 ('poroshenko', 177),
 ("'script'", 175),
 ('trumpcare', 174),
 ('gabbard', 174),
 ('hensarling', 173),
 ('schaeuble', 172),
 ('thaad', 170),
 ('lahren', 170),
 ('lighthizer', 168),
 ('odebrecht', 167),
 ('pinera', 167),
 ("'facebook", 167),
 ("jssdk'", 167),
 ('nasralla', 166),
 ('cnrp', 165),
 ('dlamini', 161),
 ('sekulow', 159),
 ('nowicki', 159),
 ('zeid', 158),
 ('blacklivesmatter', 158),
 ('cliven', 154),
 ('foxandfriends', 151),
 ('warmbier', 150),
 ('pizzagate', 149),
 ('corbyn', 148),
 ('lavoy', 148),
 ('fattah', 146),
 ('robart', 146),
 ('strzok', 146),
 ('stelter', 144),
 ('kiir', 143),
 ('varadkar', 143),
 ('pdvsa', 141),
 ('kobach', 140),
 ('deplorables', 139),
 ('obrador', 134),
 ('navalny', 134),
 ('crowdstrike', 133),
 ('jcpoa', 133),
 ('interfax', 129),
 ('sarahpalinusa', 126),
 ('ivankatrump', 124),
 ('ardern', 124),
 ('sigmar', 123),
 ('broaddrick', 123),
 ('zaghari', 123),
 ('mladic', 122),
 ('sasse', 122),
 ('irgc', 120),
 ('rossello', 119),
 ('flotus', 119),
 ('nevertrump', 119),
 ('posobiec', 118),
 ('magnitsky', 117),
 ('haftar', 117),
 ('galizia', 117),
 ('fethullah', 116),
 ('videgaray', 116),
 ('stoltenberg', 114),
 ('steinmeier', 112),
 ('scavino', 111),
 ('eichenwald', 111),
 ('coveney', 109),
 ('pirro', 109),
 ('gianforte', 108),
 ('yingluck', 108),
 ('zeifman', 108),
 ('mogherini', 107),
 ('steinle', 107),
 ('cavusoglu', 106),
 ('farenthold', 105),
 ('kasowitz', 105),
 ('strache', 105),
 ('reut', 104),
 ('shkreli', 104),
 ('corfman', 103),
 ('khizr', 103),
 ('schlafly', 103),
 ('ghouta', 102),
 ('kcna', 101),
 ('polictally', 101),
 ('jubeir', 99),
 ('anncoulter', 99),
 ('elizabethforma', 99),
 ('jbh', 98),
 ('jpexyr', 98),
 ('rosneft', 97),
 ('jonben', 96),
 ('guillier', 95),
 ('jordanuhl', 94),
 ('kfnx', 94),
 ('goodlatte', 93),
 ('rosatom', 93),
 ('bessbell', 92),
 ('ryabkov', 91),
 ('koskinen', 90),
 ('speakerryan', 90),
 ('tonyposnanski', 89),
 ('cfius', 88),
 ('mursi', 88),
 ('widodo', 88),
 ('schlussel', 88),
 ('timberg', 88),
 ('sechin', 87),
 ('sirleaf', 87),
 ('bachelet', 86),
 ('novanto', 86),
 ('spreaker', 86),
 ('sulaimaniya', 85),
 ('presssec', 85),
 ('loomer', 85),
 ('baghdadi', 84),
 ('wildstein', 84),
 ('alperovitch', 84),
 ('icrc', 83),
 ('iarc', 82),
 ('ayyadurai', 82),
 ('bonifield', 82),
 ('sheikhoun', 81),
 ('posnanski', 81),
 ('raddatz', 80),
 ('chunying', 79),
 ('sabratha', 79),
 ('toensing', 78),
 ('morawiecki', 78),
 ('saipov', 77),
 ('kochs', 77),
 ('ttip', 77),
 ('rohrabacher', 76),
 ('mcgahn', 76),
 ('prayuth', 76),
 ('onewest', 76),
 ('daleiden', 76),
 ('szydlo', 76),
 ('hodeidah', 76),
 ('bergdahl', 75),
 ('gentiloni', 75),
 ('russiagate', 75),
 ('steyer', 74),
 ('branstad', 74),
 ('heitkamp', 73),
 ('zakharova', 73),
 ('chiwenga', 73),
 ('chombo', 73),
 ('matthewdicks', 73),
 ('opcw', 72),
 ('alwaleed', 72),
 ('jobbik', 72),
 ('talabani', 72),
 ('tantaros', 72),
 ('propornot', 72),
 ('shaub', 71),
 ('fakenews', 71),
 ('santilli', 71),
 ('bhumibol', 70),
 ('rousseff', 70),
 ('jackposobiec', 70),
 ('tawhidi', 70),
 ('jaysanalysis', 70),
 ('grenfell', 69),
 ('schakowsky', 68),
 ('mossos', 68),
 ('stachowiak', 68),
 ('bartiromo', 67),
 ('amash', 67),
 ('gauland', 67),
 ('rohingyas', 67),
 ('kilmeade', 66),
 ('mezvinsky', 66),
 ('fidesz', 66),
 ('soleimani', 65),
 ('petrovietnam', 65),
 ('rahami', 65),
 ('akihito', 64),
 ('dandong', 64),
 ('berniesanders', 64),
 ('ulyukayev', 64),
 ('douliery', 64),
 ('abcpolitics', 64),
 ('joshdcaplan', 64),
 ('tsarnaev', 64),
 ('rtread', 64),
 ('boakai', 63),
 ('binali', 62),
 ('bossert', 62),
 ('donaldjtrumpjr', 62),
 ('tedcruz', 62),
 ('gopers', 62),
 ('klobuchar', 61),
 ('gohmert', 61),
 ('stabenow', 61),
 ('arakan', 61),
 ('maute', 61),
 ('timmermans', 60),
 ('janot', 60),
 ('braddjaffy', 60),
 ('\t', 59),
 ('guajardo', 59),
 ('tasnim', 59),
 ('mevlut', 59),
 ('rabbu', 59),
 ('hapilon', 59),
 ('shafik', 59),
 ('walshfreedom', 59),
 ('orrick', 58),
 ('hlaing', 58),
 ('hawija', 58),
 ('gchq', 58),
 ('bridgegate', 58),
 ('kellyannepolls', 58),
 ('pagliano', 58),
 ('gnassingbe', 58),
 ('harrer', 58),
 ('hwasong', 57),
 ('mccaul', 57),
 ('predictit', 57),
 ('feltman', 57),
 ('mcenany', 57),
 ('speier', 56),
 ('zapad', 56),
 ('mcaleer', 56),
 ('liangelo', 55),
 ('melgen', 55),
 ('delrahim', 55),
 ('seehofer', 55),
 ('marcorubio', 55),
 ('mikerin', 55),
 ('fransen', 54),
 ('htay', 54),
 ('staffan', 54),
 ('shaaban', 54),
 ('halkbank', 54),
 ('thedcnf', 54),
 ('bamn', 54),
 ('yanukovych', 53),
 ('mukasey', 53),
 ('ahca', 53),
 ('philando', 53),
 ('labaik', 53),
 ('teigen', 53),
 ('boente', 52),
 ('schuette', 52),
 ('cnnpolitics', 52),
 ('bolduan', 52),
 ('igorvolsky', 52),
 ('wictor', 52),
 ('zimdars', 52),
 ('scotusblog', 51),
 ('maungdaw', 51),
 ('phelim', 51),
 ('jaffy', 51),
 ('bundys', 51),
 ('sununu', 50),
 ('leyen', 50),
 ('nigerien', 50),
 ('valeant', 49),
 ('abedini', 49),
 ('nehlen', 49),
 ('kovaleski', 49),
 ('naypyitaw', 48),
 ('yougov', 48),
 ('harward', 48),
 ('mirziyoyev', 48),
 ('jafari', 48),
 ('shinawatra', 48),
 ('balbi', 48),
 ('phoenixnewtimes', 48),
 ('wikicommons', 48),
 ('manigault', 47),
 ('nebenzia', 47),
 ('aqap', 47),
 ('afari', 47),
 ('assata', 47),
 ('sittwe', 47),
 ('kerimov', 47),
 ('senwarren', 47),
 ('sarsour', 47),
 ('digenova', 47),
 ('barrasso', 46),
 ('iowans', 46),
 ('gofundme', 46),
 ('covfefe', 46),
 ('stavridis', 46),
 ('wauquiez', 46),
 ('ritzheimer', 46),
 ('grutter', 46),
 ('futerfas', 45),
 ('yonhap', 45),
 ('melenchon', 45),
 ('sayyaf', 45),
 ('ozdemir', 45),
 ('pottinger', 45),
 ('qaim', 45),
 ('ohchr', 45),
 ('kylegriffin', 45),
 ('deblasio', 45),
 ('zervos', 44),
 ('twtr', 44),
 ('abedi', 44),
 ('amaq', 44),
 ('altmaier', 44),
 ('mohamud', 44),
 ('felarca', 44),
 ('chesimard', 44),
 ('vowg', 43),
 ('kelner', 43),
 ('qassem', 43),
 ('tashfeen', 43),
 ('nkosazana', 43),
 ('diamondandsilk', 43),
 ('kadyrov', 43),
 ('velayati', 43),
 ('tehreek', 43),
 ('raufkhon', 43),
 ('konashenkov', 43),
 ('seanspicer', 43),
 ('kurteichenwald', 43),
 ('stephenking', 43),
 ('soeiro', 43),
 ('trumpers', 42),
 ('tsipras', 42),
 ('caglayan', 42),
 ('shulkin', 42),
 ('disruptj', 42),
 ('verhofstadt', 42),
 ('odni', 42),
 ('junqueras', 42),
 ('cicig', 42),
 ('newsread', 42),
 ('crisiscast', 42),
 ('yanukovich', 41),
 ('weidel', 41),
 ('dimicco', 41),
 ('splc', 41),
 ('misrata', 41),
 ('gwadar', 41),
 ('sistani', 41),
 ('magufuli', 41),
 ('dabbashi', 41),
 ('gutfeld', 41),
 ('nuland', 40),
 ('donbass', 40),
 ('megynkelly', 40),
 ('delemus', 40),
 ('djalali', 40),
 ('maraga', 40),
 ('jemele', 40),
 ('erictrump', 40),
 ('merriamwebster', 40),
 ('binney', 40),
 ('permindex', 40),
 ('suchomel', 40),
 ('kinzinger', 39),
 ('trumptrain', 39),
 ('shoigu', 39),
 ('seddique', 39),
 ('psdb', 39),
 ('jollett', 39),
 ('ruhle', 39),
 ('theresistance', 39),
 ('neiltyson', 39),
 ('pattonoswalt', 39),
 ('fven', 39),
 ('martland', 39),
 ('cardillo', 38),
 ('chelseaclinton', 38),
 ('dilma', 38),
 ('guptas', 38),
 ('forcadell', 38),
 ('riina', 38),
 ('bigly', 38),
 ('dylann', 38),
 ('aprildryan', 38),
 ('thomaswictor', 38),
 ('mrctv', 38),
 ('stoynoff', 37),
 ('yemenis', 37),
 ('onodera', 37),
 ('yoshihide', 37),
 ('trumka', 37),
 ('oatis', 37),
 ('karimov', 37),
 ('rutte', 37),
 ('miteb', 37),
 ('tweetstorm', 37),
 ('loesch', 37),
 ('trumpkins', 37),
 ('pourmecoffee', 37),
 ('newshere', 37),
 ('dimassimo', 37),
 ('kthopkins', 37),
 ('stemexpress', 37),
 ('qosi', 37),
 ('obamatrade', 37),
 ('riek', 36),
 ('donaldtrump', 36),
 ('giustra', 36),
 ('combetta', 36),
 ('hanen', 36),
 ('chiacu', 36),
 ('danscavino', 36),
 ('egeland', 36),
 ('kabunin', 36),
 ('brumskine', 36),
 ('sochua', 36),
 ('laurenduca', 36),
 ('dudich', 36),
 ('lacapria', 36),
 ('moncrief', 36),
 ('funksoul', 36),
 ('beeley', 36),
 ('nffa', 36),
 ('coie', 35),
 ('curbelo', 35),
 ('pyeongchang', 35),
 ('crookedhillary', 35),
 ('philippot', 35),
 ('ebell', 35),
 ('shayrat', 35),
 ('kyodo', 35),
 ('yoweri', 35),
 ('ccdi', 35),
 ('mayadin', 35),
 ('tomilahren', 35),
 ('fahrenthold', 35),
 ('freso', 35),
 ('vidme', 35),
 ('womensmarch', 35),
 ('realjameswoods', 35),
 ('duyne', 35),
 ('volags', 35),
 ('wirethe', 35),
 ('maloni', 34),
 ('prevezon', 34),
 ('aumf', 34),
 ('nunberg', 34),
 ('lorenzana', 34),
 ('muhammadu', 34),
 ('haradinaj', 34),
 ('bozdag', 34),
 ('habur', 34),
 ('rwigara', 34),
 ('newtgingrich', 34),
 ('salda', 34),
 ('gerritson', 34),
 ('superbody', 33),
 ('chrystia', 33),
 ('bonjean', 33),
 ('hillyer', 33),
 ('jabhat', 33),
 ('sobchak', 33),
 ('vittert', 33),
 ('abfalecbaldwin', 33),
 ('islamberg', 33),
 ('otms', 33),
 ('khdeir', 33),
 ('tetzner', 33),
 ('weissmann', 32),
 ('staver', 32),
 ('lehtinen', 32),
 ('hijazi', 32),
 ('grasberg', 32),
 ('vajiralongkorn', 32),
 ('brokenshire', 32),
 ('collomb', 32),
 ('jaketapper', 32),
 ('georgetakei', 32),
 ('newsthe', 32),
 ('goper', 32),
 ('mrny', 32),
 ('eberwein', 32),
 ('stockmonsterusa', 32),
 ('tamerlan', 32),
 ('nomani', 32),
 ('brezler', 32),
 ('heresupport', 32),
 ('chalabi', 32),
 ('petrocelli', 31),
 ('alptekin', 31),
 ('everytown', 31),
 ('schwarzman', 31),
 ('adulyadej', 31),
 ('herridge', 31),
 ('hekmati', 31),
 ('mailonline', 31),
 ('clintonemail', 31),
 ('araoz', 31),
 ('mkhize', 31),
 ('slager', 31),
 ('juchitan', 31),
 ('simonhedlin', 31),
 ('dennard', 31),
 ('bongino', 31),
 ('piwowar', 30),
 ('vassily', 30),
 ('korkmaz', 30),
 ('trumpian', 30),
 ('malpass', 30),
 ('aynrandpaulryan', 30),
 ('neera', 30),
 ('hegseth', 30),
 ('vucic', 30),
 ('dobias', 30),
 ('tajani', 30),
 ('abdullahi', 30),
 ('meirelles', 30),
 ('ouattara', 30),
 ('dahlan', 30),
 ('azirul', 30),
 ('babanov', 30),
 ('trumpchicken', 30),
 ('hedlin', 30),
 ('lawnewz', 30),
 ('jamesokeefeiii', 30),
 ('banzhaf', 30),
 ('zemmour', 30),
 ('copson', 29),
 ('handelsblatt', 29),
 ('rcep', 29),
 ('lyft', 29),
 ('keqiang', 29),
 ('fireeye', 29),
 ('beshear', 29),
 ('mayadeen', 29),
 ('betsydevos', 29),
 ('gattine', 29),
 ('gopdebate', 29),
 ('bassil', 29),
 ('nurmantyo', 29),
 ('rudaw', 29),
 ('maiziere', 29),
 ('pdecat', 29),
 ('erickfernandez', 29),
 ('trumphotels', 29),
 ('legrier', 29),
 ('senatemajldr', 28),
 ('grijalva', 28),
 ('seraj', 28),
 ('dubke', 28),
 ('jiechi', 28),
 ('pahor', 28),
 ('ayrault', 28),
 ('heldman', 28),
 ('senschumer', 28),
 ('kunduz', 28),
 ('dragnea', 28),
 ('sinjar', 28),
 ('praljak', 28),
 ('chinamasa', 28),
 ('rathedaung', 28),
 ('ocalan', 28),
 ('romatet', 28),
 ('kubicki', 28),
 ('sunstein', 28),
 ('obergefell', 28),
 ('joenbc', 28),
 ('zeleny', 28),
 ('therickwilson', 28),
 ('earhardt', 28),
 ('mskristinawong', 28),
 ('cnnblackmail', 28),
 ('arreguin', 28),
 ('henwood', 28),
 ('broadstreet', 28),
 ('46707', 28),
 ('agalarov', 27),
 ('gaetz', 27),
 ('jadwat', 27),
 ('centene', 27),
 ('rahimi', 27),
 ('namazi', 27),
 ('cuccinelli', 27),
 ('kalanick', 27),
 ('qataris', 27),
 ('califf', 27),
 ('valdmanis', 27),
 ('shaunking', 27),
 ('tunisians', 27),
 ('abdirahman', 27),
 ('jaroslaw', 27),
 ('cfdt', 27),
 ('pyin', 27),
 ('trumprussia', 27),
 ('toobin', 27),
 ('jysexton', 27),
 ('justinhendrix', 27),
 ('alefantis', 27),
 ('gerster', 27),
 ('thedc', 27),
 ('capehart', 27),
 ('gatestone', 27),
 ('rosenworcel', 26),
 ('guadagno', 26),
 ('delauro', 26),
 ('myeshia', 26),
 ('arreaza', 26),
 ('fsoc', 26),
 ('balart', 26),
 ('niinisto', 26),
 ('dujarric', 26),
 ('fukumoto', 26),
 ('musab', 26),
 ('suprun', 26),
 ('luhansk', 26),
 ('buthidaung', 26),
 ('yazidi', 26),
 ('mutsvangwa', 26),
 ('bullrich', 26),
 ('ipob', 26),
 ('khabur', 26),
 ('caixabank', 26),
 ('senjohnmccain', 26),
 ('chrismurphyct', 26),
 ('scahill', 26),
 ('chrissyteigen', 26),
 ('hbcus', 26),
 ('azalben', 26),
 ('roguepotusstaff', 26),
 ('abfoundation', 26),
 ('altusnatparkservice', 26),
 ('tischer', 26),
 ('katrinapierson', 26),
 ('aclj', 26),
 ('imamofpeace', 26),
 ('matrisciana', 26),
 ('rulesforwomensmarch', 26),
 ('tresa', 26),
 ('baldas', 26),
 ('tbaldas', 26),
 ('sipri', 26),
 ('kouachi', 26),
 ('khadr', 26),
 ('calvillo', 26),
 ('vltchek', 26),
 ('stcenturywire', 26),
 ('sibur', 25),
 ('sayfullo', 25),
 ('yukiya', 25),
 ('rossiya', 25),
 ('verrilli', 25),
 ('bleachbit', 25),
 ('repjohnlewis', 25),
 ('senecal', 25),
 ('cassella', 25),
 ('maiduguri', 25),
 ('dapl', 25),
 ('zalben', 25),
 ('basedmonitored', 25),
 ('matthaig', 25),
 ('housegop', 25),
 ('zehaf', 25),
 ('guant', 25),
 ('keilar', 25),
 ("'keefe", 25),
 ('lifezette', 25),
 ('atensnut', 25),
 ('higbie', 25),
 ('nucatola', 25),
 ('isakson', 24),
 ('yulin', 24),
 ('itsunori', 24),
 ('rezaian', 24),
 ('makeamericagreatagain', 24),
 ('americafirst', 24),
 ('iohannis', 24),
 ('uighurs', 24),
 ('watnick', 24),
 ('kerlikowske', 24),
 ('icj', 24),
 ('szijjarto', 24),
 ('huelskamp', 24),
 ('mikulski', 24),
 ('heimbach', 24),
 ('glennbeck', 24),
 ('eitc', 24),
 ('canikli', 24),
 ('jeenbekov', 24),
 ('isnilon', 24),
 ('warsame', 24),
 ('qasemi', 24),
 ('cdpj', 24),
 ('pzu', 24),
 ('bamenda', 24),
 ('wukan', 24),
 ('baswedan', 24),
 ('danley', 24),
 ('damond', 24),
 ("'reilly", 24),
 ('mikd', 24),
 ('kallstrom', 24),
 ('bettemidler', 24),
 ('altnatparkser', 24),
 ('ioffe', 24),
 ('sansaricq', 24),
 ('persinger', 24),
 ('gses', 24),
 ('mystal', 24),
 ('sarder', 24),
 ('fragos', 24),
 ('bibeau', 24),
 ('guardianread', 24),
 ('hondurans', 23),
 ('fayez', 23),
 ('ratko', 23),
 ('wannacry', 23),
 ('glencore', 23),
 ('ildefonso', 23),
 ('mcgoldrick', 23),
 ('knoller', 23),
 ('saffir', 23),
 ('grenell', 23),
 ('mcfaul', 23),
 ('gorelick', 23),
 ('marchionne', 23),
 ('gerasimov', 23),
 ('aderholt', 23),
 ('bardack', 23),
 ('hamdallah', 23),
 ('niamey', 23),
 ('teneo', 23),
 ('igad', 23),
 ('vizcarra', 23),
 ('kutupalong', 23),
 ('erdo', 23),
 ('vinnik', 23),
 ('baqeri', 23),
 ('rainsy', 23),
 ('benediktsson', 23),
 ('mawarire', 23),
 ('chebukati', 23),
 ("'https", 23),
 ('hoft', 23),
 ('gubarev', 23),
 ('rolandscahill', 23),
 ('andersoncooper', 23),
 ('brianstelter', 23),
 ('jasoninthehouse', 23),
 ('jeffreyguterman', 23),
 ('johncleese', 23),
 ('nataliemaines', 23),
 ('attaker', 23),
 ('whywomendontreport', 23),
 ('kaveladze', 22),
 ('zoomph', 22),
 ('pascrell', 22),
 ('schlapp', 22),
 ('lipnic', 22),
 ('inovo', 22),
 ('numbersusa', 22),
 ('nixonian', 22),
 ('behrouz', 22),
 ('nextera', 22),
 ('bildt', 22),
 ('oahe', 22),
 ('kermanshah', 22),
 ('deploraball', 22),
 ('connaughton', 22),
 ('nisman', 22),
 ('nechirvan', 22),
 ('chahed', 22),
 ('jumblatt', 22),
 ('castaner', 22),
 ('qishan', 22),
 ('agrokor', 22),
 ('hennis', 22),
 ('levashov', 22),
 ('schnatter', 22),
 ('pappiness', 22),
 ('robertmaguire', 22),
 ('pixabay', 22),
 ('carltischer', 22),
 ('podestaemails', 22),
 ('mccaughey', 22),
 ('martinshkreli', 22),
 ('stranahan', 22),
 ('dbloom', 22),
 ('veryfakenews', 22),
 ('klausutis', 22),
 ('listhaug', 22),
 ('mostyn', 22),
 ('garrow', 22),
 ('qadhafi', 22),
 ('ringgenberg', 22),
 ('russum', 22),
 ('kazikhani', 22),
 ('filesread', 22),
 ('mundt', 22),
 ('theshadowbrokers', 22),
 ('churkin', 21),
 ('lapan', 21),
 ('swalwell', 21),
 ('frauke', 21),
 ('parisagreement', 21),
 ('muilenburg', 21),
 ('cullerton', 21),
 ('akhmetshin', 21),
 ('kildee', 21),
 ('peduto', 21),
 ('sokolich', 21),
 ('daugaard', 21),
 ('yazidis', 21),
 ('gennifer', 21),
 ('capriles', 21),
 ('dahir', 21),
 ('teachout', 21),
 ('malzberg', 21),
 ('abdeslam', 21),
 ('bolsonaro', 21),
 ('joesley', 21),
 ('larijani', 21),
 ('pdea', 21),
 ('johannesson', 21),
 ('dastis', 21),
 ('salic', 21),
 ('villavicencio', 21),
 ('klippenstein', 21),
 ('kenklippenstein', 21),
 ('parkermolloy', 21),
 ('suzdaltsev', 21),
 ('keitholbermann', 21),
 ('kharyp', 21),
 ('drumpf', 21),
 ('julianassange', 21),
 ('imwithher', 21),
 ('aravosis', 21),
 ('ammosexual', 21),
 ('popick', 21),
 ('ackal', 21),
 ('presidentobamanotbarry', 21),
 ('hiddenspellerror', 21),
 ('andwhereas', 21),
 ('alawa', 21),
 ('nbpc', 21),
 ('aslani', 21),
 ('abasaslani', 21),
 ('tyshawn', 21),
 ('khaqan', 20),
 ('enzi', 20),
 ('mackowiak', 20),
 ('sueddeutsche', 20),
 ('holmstead', 20),
 ('lovells', 20),
 ('vladeck', 20),
 ('chemchina', 20),
 ('fraudnewscnn', 20),
 ('laquan', 20),
 ('epshteyn', 20),
 ('boochani', 20),
 ('gergen', 20),
 ('marsudi', 20),
 ('alabedbana', 20),
 ('szubin', 20),
 ('dcleaks', 20),
 ('trumpism', 20),
 ('gilberthorpe', 20),
 ('mciver', 20),
 ('caitlan', 20),
 ('karadzic', 20),
 ('yucel', 20),
 ('monusco', 20),
 ('bennelong', 20),
 ('lozoya', 20),
 ('haniyeh', 20),
 ('bouteflika', 20),
 ('starmer', 20),
 ('bekir', 20),
 ('lowcock', 20),
 ('sabhan', 20),
 ('burundian', 20),
 ('derna', 20),
 ('brawner', 20),
 ('louren', 20),
 ('readle', 20),
 ('missmayn', 20),
 ('maxinewaters', 20),
 ('khary', 20),
 ('penebaker', 20),
 ('sethabramson', 20),
 ('wdfx', 20),
 ('muscato', 20),
 ('erovinkin', 20),
 ('soleia', 20),
 ('goldenglobes', 20),
 ('inquisitr', 20),
 ('billclinton', 20),
 ('foxbusiness', 20),
 ('nydn', 20),
 ('spusa', 20),
 ('lorich', 20),
 ('emptyseatspics', 20),
 ('breakingnlive', 20),
 ('berkland', 20),
 ('newttrump', 20),
 ('etue', 20),
 ('isbr', 20),
 ('viviano', 20),
 ('vcdl', 20),
 ('froglegs', 20),
 ('peymani', 20),
 ('cruiz', 20),
 ('ushakov', 19),
 ('noreika', 19),
 ('katsyv', 19),
 ('guttmacher', 19),
 ('krikorian', 19),
 ('liveris', 19),
 ('pawlowski', 19),
 ('barazi', 19),
 ('medecins', 19),
 ('kadzik', 19),
 ('punggye', 19),
 ('bylock', 19),
 ('kurram', 19),
 ('junts', 19),
 ('inacio', 19),
 ('alckmin', 19),
 ('rafah', 19),
 ('compaore', 19),
 ('hyon', 19),
 ('lavrentyev', 19),
 ('esquadra', 19),
 ('semenya', 19),
 ('katerji', 19),
 ('smartmatic', 19),
 ('kompromat', 19),
 ('cassandrarules', 19),
 ('boycottbudwiser', 19),
 ('statsky', 19),
 ('ingrahamangle', 19),
 ('cullors', 19),
 ('perticone', 19),
 ...]

In [37]:
cc.checkCoverage(array_text2)

100%|██████████████████████████████████████████████████████████████████████████| 44898/44898 [00:05<00:00, 8569.55it/s]
100%|█████████████████████████████████████████████████████████████████████| 118935/118935 [00:00<00:00, 1046043.02it/s]

the number of distinct vocabulary of data is 118935
In Embedding Index we have 61.26% coverage of distinct vocabulary
And we have 99.14% coverage of all text
The number of words which are not covered in GloVe resource is: 46076

[('\xa0', 5173),
 ('realdonaldtrump', 4627),
 ('tillerson', 2783),
 ('brexit', 2147),
 ('rohingya', 2055),
 ('manafort', 1235),
 ("'t", 1002),
 ('mnuchin', 980),
 ('gorsuch', 965),
 ('rakhine', 897),
 ('priebus', 872),
 ('duterte', 868),
 ('raqqa', 694),
 ('puigdemont', 645),
 ('filessupport', 594),
 ('jinping', 567),
 ('kellyanne', 553),
 ('abedin', 542),
 ('lavrov', 511),
 ('scaramucci', 504),
 ('reince', 482),
 ('somodevilla', 466),
 ('rosenstein', 447),
 ('chaffetz', 413),
 ('mnangagwa', 403),
 ('mulvaney', 391),
 ('henningsen', 390),
 ('blasio', 384),
 ('houthis', 384),
 ('finicum', 361),
 ('gulen', 354),
 ('houthi', 351),
 ('peskov', 350),
 ('juncker', 347),
 ('scalise', 340),
 ('tmsnrt', 338),
 ('kuczynski', 338),
 ('kislyak', 338),
 ('cfpb', 334),
 ('rouhani', 325),
 ('rauner', 323),
 ('ramaphosa', 288),
 ('barzani', 286),
 ('barnier', 284),
 ('angerer', 281),
 ('idlib', 276),
 ('hillaryclinton', 271),
 ('veselnitskaya', 269),
 ('yellen', 263),
 ('macri', 263),
 ('zinke', 261),
 ('marawi', 255),
 ('guterres', 252),
 ('nusra', 238),
 ('seanhannity', 235),
 ('guccifer', 223),
 ('yiannopoulos', 223),
 ('zarrab', 217),
 ('sokha', 217),
 ('isil', 217),
 ('daesh', 214),
 ('puzder', 211),
 ('nauert', 209),
 ('raedle', 200),
 ('cernovich', 194),
 ('curiel', 191),
 ('mcmullin', 186),
 ('ossoff', 184),
 ('bharara', 178),
 ('poroshenko', 177),
 ("'script'", 175),
 ('trumpcare', 174),
 ('gabbard', 174),
 ('hensarling', 173),
 ('schaeuble', 172),
 ('thaad', 170),
 ('lahren', 170),
 ('lighthizer', 168),
 ('odebrecht', 167),
 ('pinera', 167),
 ("'facebook", 167),
 ("jssdk'", 167),
 ('nasralla', 166),
 ('cnrp', 165),
 ('dlamini', 161),
 ('sekulow', 159),
 ('nowicki', 159),
 ('zeid', 158),
 ('blacklivesmatter', 158),
 ('cliven', 154),
 ('foxandfriends', 151),
 ('warmbier', 150),
 ('pizzagate', 149),
 ('corbyn', 148),
 ('lavoy', 148),
 ('fattah', 146),
 ('robart', 146),
 ('strzok', 146),
 ('stelter', 144),
 ('kiir', 143),
 ('varadkar', 143),
 ('pdvsa', 141),
 ('kobach', 140),
 ('deplorables', 139),
 ('obrador', 134),
 ('navalny', 134),
 ('crowdstrike', 133),
 ('jcpoa', 133),
 ('interfax', 129),
 ('sarahpalinusa', 126),
 ('ivankatrump', 124),
 ('ardern', 124),
 ('sigmar', 123),
 ('broaddrick', 123),
 ('zaghari', 123),
 ('mladic', 122),
 ('sasse', 122),
 ('irgc', 120),
 ('rossello', 119),
 ('flotus', 119),
 ('nevertrump', 119),
 ('posobiec', 118),
 ('magnitsky', 117),
 ('haftar', 117),
 ('galizia', 117),
 ('fethullah', 116),
 ('videgaray', 116),
 ('stoltenberg', 114),
 ('steinmeier', 112),
 ('scavino', 111),
 ('eichenwald', 111),
 ('coveney', 109),
 ('pirro', 109),
 ('gianforte', 108),
 ('yingluck', 108),
 ('zeifman', 108),
 ('mogherini', 107),
 ('steinle', 107),
 ('cavusoglu', 106),
 ('farenthold', 105),
 ('kasowitz', 105),
 ('strache', 105),
 ('reut', 104),
 ('shkreli', 104),
 ('corfman', 103),
 ('khizr', 103),
 ('schlafly', 103),
 ('ghouta', 102),
 ('kcna', 101),
 ('polictally', 101),
 ('jubeir', 99),
 ('anncoulter', 99),
 ('elizabethforma', 99),
 ('jbh', 98),
 ('jpexyr', 98),
 ('rosneft', 97),
 ('jonben', 96),
 ('guillier', 95),
 ('jordanuhl', 94),
 ('kfnx', 94),
 ('goodlatte', 93),
 ('rosatom', 93),
 ('bessbell', 92),
 ('ryabkov', 91),
 ('koskinen', 90),
 ('speakerryan', 90),
 ('tonyposnanski', 89),
 ('cfius', 88),
 ('mursi', 88),
 ('widodo', 88),
 ('schlussel', 88),
 ('timberg', 88),
 ('sechin', 87),
 ('sirleaf', 87),
 ('bachelet', 86),
 ('novanto', 86),
 ('spreaker', 86),
 ('sulaimaniya', 85),
 ('presssec', 85),
 ('loomer', 85),
 ('baghdadi', 84),
 ('wildstein', 84),
 ('alperovitch', 84),
 ('icrc', 83),
 ('iarc', 82),
 ('ayyadurai', 82),
 ('bonifield', 82),
 ('sheikhoun', 81),
 ('posnanski', 81),
 ('raddatz', 80),
 ('chunying', 79),
 ('sabratha', 79),
 ('toensing', 78),
 ('morawiecki', 78),
 ('saipov', 77),
 ('kochs', 77),
 ('ttip', 77),
 ('rohrabacher', 76),
 ('mcgahn', 76),
 ('prayuth', 76),
 ('onewest', 76),
 ('daleiden', 76),
 ('szydlo', 76),
 ('hodeidah', 76),
 ('bergdahl', 75),
 ('gentiloni', 75),
 ('russiagate', 75),
 ('steyer', 74),
 ('branstad', 74),
 ('heitkamp', 73),
 ('zakharova', 73),
 ('chiwenga', 73),
 ('chombo', 73),
 ('matthewdicks', 73),
 ('opcw', 72),
 ('alwaleed', 72),
 ('jobbik', 72),
 ('talabani', 72),
 ('tantaros', 72),
 ('propornot', 72),
 ('shaub', 71),
 ('fakenews', 71),
 ('santilli', 71),
 ('bhumibol', 70),
 ('rousseff', 70),
 ('jackposobiec', 70),
 ('tawhidi', 70),
 ('jaysanalysis', 70),
 ('grenfell', 69),
 ('schakowsky', 68),
 ('mossos', 68),
 ('stachowiak', 68),
 ('bartiromo', 67),
 ('amash', 67),
 ('gauland', 67),
 ('rohingyas', 67),
 ('kilmeade', 66),
 ('mezvinsky', 66),
 ('fidesz', 66),
 ('soleimani', 65),
 ('petrovietnam', 65),
 ('rahami', 65),
 ('akihito', 64),
 ('dandong', 64),
 ('berniesanders', 64),
 ('ulyukayev', 64),
 ('douliery', 64),
 ('abcpolitics', 64),
 ('joshdcaplan', 64),
 ('tsarnaev', 64),
 ('rtread', 64),
 ('boakai', 63),
 ('binali', 62),
 ('bossert', 62),
 ('donaldjtrumpjr', 62),
 ('tedcruz', 62),
 ('gopers', 62),
 ('klobuchar', 61),
 ('gohmert', 61),
 ('stabenow', 61),
 ('arakan', 61),
 ('maute', 61),
 ('timmermans', 60),
 ('janot', 60),
 ('braddjaffy', 60),
 ('\t', 59),
 ('guajardo', 59),
 ('tasnim', 59),
 ('mevlut', 59),
 ('rabbu', 59),
 ('hapilon', 59),
 ('shafik', 59),
 ('walshfreedom', 59),
 ('orrick', 58),
 ('hlaing', 58),
 ('hawija', 58),
 ('gchq', 58),
 ('bridgegate', 58),
 ('kellyannepolls', 58),
 ('pagliano', 58),
 ('gnassingbe', 58),
 ('harrer', 58),
 ('hwasong', 57),
 ('mccaul', 57),
 ('predictit', 57),
 ('feltman', 57),
 ('mcenany', 57),
 ('speier', 56),
 ('zapad', 56),
 ('mcaleer', 56),
 ('liangelo', 55),
 ('melgen', 55),
 ('delrahim', 55),
 ('seehofer', 55),
 ('marcorubio', 55),
 ('mikerin', 55),
 ('fransen', 54),
 ('htay', 54),
 ('staffan', 54),
 ('shaaban', 54),
 ('halkbank', 54),
 ('thedcnf', 54),
 ('bamn', 54),
 ('yanukovych', 53),
 ('mukasey', 53),
 ('ahca', 53),
 ('philando', 53),
 ('labaik', 53),
 ('teigen', 53),
 ('boente', 52),
 ('schuette', 52),
 ('cnnpolitics', 52),
 ('bolduan', 52),
 ('igorvolsky', 52),
 ('wictor', 52),
 ('zimdars', 52),
 ('scotusblog', 51),
 ('maungdaw', 51),
 ('phelim', 51),
 ('jaffy', 51),
 ('bundys', 51),
 ('sununu', 50),
 ('leyen', 50),
 ('nigerien', 50),
 ('valeant', 49),
 ('abedini', 49),
 ('nehlen', 49),
 ('kovaleski', 49),
 ('naypyitaw', 48),
 ('yougov', 48),
 ('harward', 48),
 ('mirziyoyev', 48),
 ('jafari', 48),
 ('shinawatra', 48),
 ('balbi', 48),
 ('phoenixnewtimes', 48),
 ('wikicommons', 48),
 ('manigault', 47),
 ('nebenzia', 47),
 ('aqap', 47),
 ('afari', 47),
 ('assata', 47),
 ('sittwe', 47),
 ('kerimov', 47),
 ('senwarren', 47),
 ('sarsour', 47),
 ('digenova', 47),
 ('barrasso', 46),
 ('iowans', 46),
 ('gofundme', 46),
 ('covfefe', 46),
 ('stavridis', 46),
 ('wauquiez', 46),
 ('ritzheimer', 46),
 ('grutter', 46),
 ('futerfas', 45),
 ('yonhap', 45),
 ('melenchon', 45),
 ('sayyaf', 45),
 ('ozdemir', 45),
 ('pottinger', 45),
 ('qaim', 45),
 ('ohchr', 45),
 ('kylegriffin', 45),
 ('deblasio', 45),
 ('zervos', 44),
 ('twtr', 44),
 ('abedi', 44),
 ('amaq', 44),
 ('altmaier', 44),
 ('mohamud', 44),
 ('felarca', 44),
 ('chesimard', 44),
 ('vowg', 43),
 ('kelner', 43),
 ('qassem', 43),
 ('tashfeen', 43),
 ('nkosazana', 43),
 ('diamondandsilk', 43),
 ('kadyrov', 43),
 ('velayati', 43),
 ('tehreek', 43),
 ('raufkhon', 43),
 ('konashenkov', 43),
 ('seanspicer', 43),
 ('kurteichenwald', 43),
 ('stephenking', 43),
 ('soeiro', 43),
 ('trumpers', 42),
 ('tsipras', 42),
 ('caglayan', 42),
 ('shulkin', 42),
 ('disruptj', 42),
 ('verhofstadt', 42),
 ('odni', 42),
 ('junqueras', 42),
 ('cicig', 42),
 ('newsread', 42),
 ('crisiscast', 42),
 ('yanukovich', 41),
 ('weidel', 41),
 ('dimicco', 41),
 ('splc', 41),
 ('misrata', 41),
 ('gwadar', 41),
 ('sistani', 41),
 ('magufuli', 41),
 ('dabbashi', 41),
 ('gutfeld', 41),
 ('nuland', 40),
 ('donbass', 40),
 ('megynkelly', 40),
 ('delemus', 40),
 ('djalali', 40),
 ('maraga', 40),
 ('jemele', 40),
 ('erictrump', 40),
 ('merriamwebster', 40),
 ('binney', 40),
 ('permindex', 40),
 ('suchomel', 40),
 ('kinzinger', 39),
 ('trumptrain', 39),
 ('shoigu', 39),
 ('seddique', 39),
 ('psdb', 39),
 ('jollett', 39),
 ('ruhle', 39),
 ('theresistance', 39),
 ('neiltyson', 39),
 ('pattonoswalt', 39),
 ('fven', 39),
 ('martland', 39),
 ('cardillo', 38),
 ('chelseaclinton', 38),
 ('dilma', 38),
 ('guptas', 38),
 ('forcadell', 38),
 ('riina', 38),
 ('bigly', 38),
 ('dylann', 38),
 ('aprildryan', 38),
 ('thomaswictor', 38),
 ('mrctv', 38),
 ('stoynoff', 37),
 ('yemenis', 37),
 ('onodera', 37),
 ('yoshihide', 37),
 ('trumka', 37),
 ('oatis', 37),
 ('karimov', 37),
 ('rutte', 37),
 ('miteb', 37),
 ('tweetstorm', 37),
 ('loesch', 37),
 ('trumpkins', 37),
 ('pourmecoffee', 37),
 ('newshere', 37),
 ('dimassimo', 37),
 ('kthopkins', 37),
 ('stemexpress', 37),
 ('qosi', 37),
 ('obamatrade', 37),
 ('riek', 36),
 ('donaldtrump', 36),
 ('giustra', 36),
 ('combetta', 36),
 ('hanen', 36),
 ('chiacu', 36),
 ('danscavino', 36),
 ('egeland', 36),
 ('kabunin', 36),
 ('brumskine', 36),
 ('sochua', 36),
 ('laurenduca', 36),
 ('dudich', 36),
 ('lacapria', 36),
 ('moncrief', 36),
 ('funksoul', 36),
 ('beeley', 36),
 ('nffa', 36),
 ('coie', 35),
 ('curbelo', 35),
 ('pyeongchang', 35),
 ('crookedhillary', 35),
 ('philippot', 35),
 ('ebell', 35),
 ('shayrat', 35),
 ('kyodo', 35),
 ('yoweri', 35),
 ('ccdi', 35),
 ('mayadin', 35),
 ('tomilahren', 35),
 ('fahrenthold', 35),
 ('freso', 35),
 ('vidme', 35),
 ('womensmarch', 35),
 ('realjameswoods', 35),
 ('duyne', 35),
 ('volags', 35),
 ('wirethe', 35),
 ('maloni', 34),
 ('prevezon', 34),
 ('aumf', 34),
 ('nunberg', 34),
 ('lorenzana', 34),
 ('muhammadu', 34),
 ('haradinaj', 34),
 ('bozdag', 34),
 ('habur', 34),
 ('rwigara', 34),
 ('newtgingrich', 34),
 ('salda', 34),
 ('gerritson', 34),
 ('superbody', 33),
 ('chrystia', 33),
 ('bonjean', 33),
 ('hillyer', 33),
 ('jabhat', 33),
 ('sobchak', 33),
 ('vittert', 33),
 ('abfalecbaldwin', 33),
 ('islamberg', 33),
 ('otms', 33),
 ('khdeir', 33),
 ('tetzner', 33),
 ('weissmann', 32),
 ('staver', 32),
 ('lehtinen', 32),
 ('hijazi', 32),
 ('grasberg', 32),
 ('vajiralongkorn', 32),
 ('brokenshire', 32),
 ('collomb', 32),
 ('jaketapper', 32),
 ('georgetakei', 32),
 ('newsthe', 32),
 ('goper', 32),
 ('mrny', 32),
 ('eberwein', 32),
 ('stockmonsterusa', 32),
 ('tamerlan', 32),
 ('nomani', 32),
 ('brezler', 32),
 ('heresupport', 32),
 ('chalabi', 32),
 ('petrocelli', 31),
 ('alptekin', 31),
 ('everytown', 31),
 ('schwarzman', 31),
 ('adulyadej', 31),
 ('herridge', 31),
 ('hekmati', 31),
 ('mailonline', 31),
 ('clintonemail', 31),
 ('araoz', 31),
 ('mkhize', 31),
 ('slager', 31),
 ('juchitan', 31),
 ('simonhedlin', 31),
 ('dennard', 31),
 ('bongino', 31),
 ('piwowar', 30),
 ('vassily', 30),
 ('korkmaz', 30),
 ('trumpian', 30),
 ('malpass', 30),
 ('aynrandpaulryan', 30),
 ('neera', 30),
 ('hegseth', 30),
 ('vucic', 30),
 ('dobias', 30),
 ('tajani', 30),
 ('abdullahi', 30),
 ('meirelles', 30),
 ('ouattara', 30),
 ('dahlan', 30),
 ('azirul', 30),
 ('babanov', 30),
 ('trumpchicken', 30),
 ('hedlin', 30),
 ('lawnewz', 30),
 ('jamesokeefeiii', 30),
 ('banzhaf', 30),
 ('zemmour', 30),
 ('copson', 29),
 ('handelsblatt', 29),
 ('rcep', 29),
 ('lyft', 29),
 ('keqiang', 29),
 ('fireeye', 29),
 ('beshear', 29),
 ('mayadeen', 29),
 ('betsydevos', 29),
 ('gattine', 29),
 ('gopdebate', 29),
 ('bassil', 29),
 ('nurmantyo', 29),
 ('rudaw', 29),
 ('maiziere', 29),
 ('pdecat', 29),
 ('erickfernandez', 29),
 ('trumphotels', 29),
 ('legrier', 29),
 ('senatemajldr', 28),
 ('grijalva', 28),
 ('seraj', 28),
 ('dubke', 28),
 ('jiechi', 28),
 ('pahor', 28),
 ('ayrault', 28),
 ('heldman', 28),
 ('senschumer', 28),
 ('kunduz', 28),
 ('dragnea', 28),
 ('sinjar', 28),
 ('praljak', 28),
 ('chinamasa', 28),
 ('rathedaung', 28),
 ('ocalan', 28),
 ('romatet', 28),
 ('kubicki', 28),
 ('sunstein', 28),
 ('obergefell', 28),
 ('joenbc', 28),
 ('zeleny', 28),
 ('therickwilson', 28),
 ('earhardt', 28),
 ('mskristinawong', 28),
 ('cnnblackmail', 28),
 ('arreguin', 28),
 ('henwood', 28),
 ('broadstreet', 28),
 ('46707', 28),
 ('agalarov', 27),
 ('gaetz', 27),
 ('jadwat', 27),
 ('centene', 27),
 ('rahimi', 27),
 ('namazi', 27),
 ('cuccinelli', 27),
 ('kalanick', 27),
 ('qataris', 27),
 ('califf', 27),
 ('valdmanis', 27),
 ('shaunking', 27),
 ('tunisians', 27),
 ('abdirahman', 27),
 ('jaroslaw', 27),
 ('cfdt', 27),
 ('pyin', 27),
 ('trumprussia', 27),
 ('toobin', 27),
 ('jysexton', 27),
 ('justinhendrix', 27),
 ('alefantis', 27),
 ('gerster', 27),
 ('thedc', 27),
 ('capehart', 27),
 ('gatestone', 27),
 ('rosenworcel', 26),
 ('guadagno', 26),
 ('delauro', 26),
 ('myeshia', 26),
 ('arreaza', 26),
 ('fsoc', 26),
 ('balart', 26),
 ('niinisto', 26),
 ('dujarric', 26),
 ('fukumoto', 26),
 ('musab', 26),
 ('suprun', 26),
 ('luhansk', 26),
 ('buthidaung', 26),
 ('yazidi', 26),
 ('mutsvangwa', 26),
 ('bullrich', 26),
 ('ipob', 26),
 ('khabur', 26),
 ('caixabank', 26),
 ('senjohnmccain', 26),
 ('chrismurphyct', 26),
 ('scahill', 26),
 ('chrissyteigen', 26),
 ('hbcus', 26),
 ('azalben', 26),
 ('roguepotusstaff', 26),
 ('abfoundation', 26),
 ('altusnatparkservice', 26),
 ('tischer', 26),
 ('katrinapierson', 26),
 ('aclj', 26),
 ('imamofpeace', 26),
 ('matrisciana', 26),
 ('rulesforwomensmarch', 26),
 ('tresa', 26),
 ('baldas', 26),
 ('tbaldas', 26),
 ('sipri', 26),
 ('kouachi', 26),
 ('khadr', 26),
 ('calvillo', 26),
 ('vltchek', 26),
 ('stcenturywire', 26),
 ('sibur', 25),
 ('sayfullo', 25),
 ('yukiya', 25),
 ('rossiya', 25),
 ('verrilli', 25),
 ('bleachbit', 25),
 ('repjohnlewis', 25),
 ('senecal', 25),
 ('cassella', 25),
 ('maiduguri', 25),
 ('dapl', 25),
 ('zalben', 25),
 ('basedmonitored', 25),
 ('matthaig', 25),
 ('housegop', 25),
 ('zehaf', 25),
 ('guant', 25),
 ('keilar', 25),
 ("'keefe", 25),
 ('lifezette', 25),
 ('atensnut', 25),
 ('higbie', 25),
 ('nucatola', 25),
 ('isakson', 24),
 ('yulin', 24),
 ('itsunori', 24),
 ('rezaian', 24),
 ('makeamericagreatagain', 24),
 ('americafirst', 24),
 ('iohannis', 24),
 ('uighurs', 24),
 ('watnick', 24),
 ('kerlikowske', 24),
 ('icj', 24),
 ('szijjarto', 24),
 ('huelskamp', 24),
 ('mikulski', 24),
 ('heimbach', 24),
 ('glennbeck', 24),
 ('eitc', 24),
 ('canikli', 24),
 ('jeenbekov', 24),
 ('isnilon', 24),
 ('warsame', 24),
 ('qasemi', 24),
 ('cdpj', 24),
 ('pzu', 24),
 ('bamenda', 24),
 ('wukan', 24),
 ('baswedan', 24),
 ('danley', 24),
 ('damond', 24),
 ("'reilly", 24),
 ('mikd', 24),
 ('kallstrom', 24),
 ('bettemidler', 24),
 ('altnatparkser', 24),
 ('ioffe', 24),
 ('sansaricq', 24),
 ('persinger', 24),
 ('gses', 24),
 ('mystal', 24),
 ('sarder', 24),
 ('fragos', 24),
 ('bibeau', 24),
 ('guardianread', 24),
 ('hondurans', 23),
 ('fayez', 23),
 ('ratko', 23),
 ('wannacry', 23),
 ('glencore', 23),
 ('ildefonso', 23),
 ('mcgoldrick', 23),
 ('knoller', 23),
 ('saffir', 23),
 ('grenell', 23),
 ('mcfaul', 23),
 ('gorelick', 23),
 ('marchionne', 23),
 ('gerasimov', 23),
 ('aderholt', 23),
 ('bardack', 23),
 ('hamdallah', 23),
 ('niamey', 23),
 ('teneo', 23),
 ('igad', 23),
 ('vizcarra', 23),
 ('kutupalong', 23),
 ('erdo', 23),
 ('vinnik', 23),
 ('baqeri', 23),
 ('rainsy', 23),
 ('benediktsson', 23),
 ('mawarire', 23),
 ('chebukati', 23),
 ("'https", 23),
 ('hoft', 23),
 ('gubarev', 23),
 ('rolandscahill', 23),
 ('andersoncooper', 23),
 ('brianstelter', 23),
 ('jasoninthehouse', 23),
 ('jeffreyguterman', 23),
 ('johncleese', 23),
 ('nataliemaines', 23),
 ('attaker', 23),
 ('whywomendontreport', 23),
 ('kaveladze', 22),
 ('zoomph', 22),
 ('pascrell', 22),
 ('schlapp', 22),
 ('lipnic', 22),
 ('inovo', 22),
 ('numbersusa', 22),
 ('nixonian', 22),
 ('behrouz', 22),
 ('nextera', 22),
 ('bildt', 22),
 ('oahe', 22),
 ('kermanshah', 22),
 ('deploraball', 22),
 ('connaughton', 22),
 ('nisman', 22),
 ('nechirvan', 22),
 ('chahed', 22),
 ('jumblatt', 22),
 ('castaner', 22),
 ('qishan', 22),
 ('agrokor', 22),
 ('hennis', 22),
 ('levashov', 22),
 ('schnatter', 22),
 ('pappiness', 22),
 ('robertmaguire', 22),
 ('pixabay', 22),
 ('carltischer', 22),
 ('podestaemails', 22),
 ('mccaughey', 22),
 ('martinshkreli', 22),
 ('stranahan', 22),
 ('dbloom', 22),
 ('veryfakenews', 22),
 ('klausutis', 22),
 ('listhaug', 22),
 ('mostyn', 22),
 ('garrow', 22),
 ('qadhafi', 22),
 ('ringgenberg', 22),
 ('russum', 22),
 ('kazikhani', 22),
 ('filesread', 22),
 ('mundt', 22),
 ('theshadowbrokers', 22),
 ('churkin', 21),
 ('lapan', 21),
 ('swalwell', 21),
 ('frauke', 21),
 ('parisagreement', 21),
 ('muilenburg', 21),
 ('cullerton', 21),
 ('akhmetshin', 21),
 ('kildee', 21),
 ('peduto', 21),
 ('sokolich', 21),
 ('daugaard', 21),
 ('yazidis', 21),
 ('gennifer', 21),
 ('capriles', 21),
 ('dahir', 21),
 ('teachout', 21),
 ('malzberg', 21),
 ('abdeslam', 21),
 ('bolsonaro', 21),
 ('joesley', 21),
 ('larijani', 21),
 ('pdea', 21),
 ('johannesson', 21),
 ('dastis', 21),
 ('salic', 21),
 ('villavicencio', 21),
 ('klippenstein', 21),
 ('kenklippenstein', 21),
 ('parkermolloy', 21),
 ('suzdaltsev', 21),
 ('keitholbermann', 21),
 ('kharyp', 21),
 ('drumpf', 21),
 ('julianassange', 21),
 ('imwithher', 21),
 ('aravosis', 21),
 ('ammosexual', 21),
 ('popick', 21),
 ('ackal', 21),
 ('presidentobamanotbarry', 21),
 ('hiddenspellerror', 21),
 ('andwhereas', 21),
 ('alawa', 21),
 ('nbpc', 21),
 ('aslani', 21),
 ('abasaslani', 21),
 ('tyshawn', 21),
 ('khaqan', 20),
 ('enzi', 20),
 ('mackowiak', 20),
 ('sueddeutsche', 20),
 ('holmstead', 20),
 ('lovells', 20),
 ('vladeck', 20),
 ('chemchina', 20),
 ('fraudnewscnn', 20),
 ('laquan', 20),
 ('epshteyn', 20),
 ('boochani', 20),
 ('gergen', 20),
 ('marsudi', 20),
 ('alabedbana', 20),
 ('szubin', 20),
 ('dcleaks', 20),
 ('trumpism', 20),
 ('gilberthorpe', 20),
 ('mciver', 20),
 ('caitlan', 20),
 ('karadzic', 20),
 ('yucel', 20),
 ('monusco', 20),
 ('bennelong', 20),
 ('lozoya', 20),
 ('haniyeh', 20),
 ('bouteflika', 20),
 ('starmer', 20),
 ('bekir', 20),
 ('lowcock', 20),
 ('sabhan', 20),
 ('burundian', 20),
 ('derna', 20),
 ('brawner', 20),
 ('louren', 20),
 ('readle', 20),
 ('missmayn', 20),
 ('maxinewaters', 20),
 ('khary', 20),
 ('penebaker', 20),
 ('sethabramson', 20),
 ('wdfx', 20),
 ('muscato', 20),
 ('erovinkin', 20),
 ('soleia', 20),
 ('goldenglobes', 20),
 ('inquisitr', 20),
 ('billclinton', 20),
 ('foxbusiness', 20),
 ('nydn', 20),
 ('spusa', 20),
 ('lorich', 20),
 ('emptyseatspics', 20),
 ('breakingnlive', 20),
 ('berkland', 20),
 ('newttrump', 20),
 ('etue', 20),
 ('isbr', 20),
 ('viviano', 20),
 ('vcdl', 20),
 ('froglegs', 20),
 ('peymani', 20),
 ('cruiz', 20),
 ('ushakov', 19),
 ('noreika', 19),
 ('katsyv', 19),
 ('guttmacher', 19),
 ('krikorian', 19),
 ('liveris', 19),
 ('pawlowski', 19),
 ('barazi', 19),
 ('medecins', 19),
 ('kadzik', 19),
 ('punggye', 19),
 ('bylock', 19),
 ('kurram', 19),
 ('junts', 19),
 ('inacio', 19),
 ('alckmin', 19),
 ('rafah', 19),
 ('compaore', 19),
 ('hyon', 19),
 ('lavrentyev', 19),
 ('esquadra', 19),
 ('semenya', 19),
 ('katerji', 19),
 ('smartmatic', 19),
 ('kompromat', 19),
 ('cassandrarules', 19),
 ('boycottbudwiser', 19),
 ('statsky', 19),
 ('ingrahamangle', 19),
 ('cullors', 19),
 ('perticone', 19),
 ...]

# 5. Concatenate the DataFrame and Storage

In [38]:
df_all

,title,text,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,1
...,...,...,...
44893,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,0
44894,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,0
44895,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,0
44896,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,0
44897,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,0

In [39]:
df_all['title'] = array_title2
df_all['text'] = array_text2

In [40]:
df_all

,title,text,label
0,"as u . s . budget fight looms , republicans fl...",washington ( reuters ) - the head of a conserv...,1
1,u . s . military to accept transgender recruit...,washington ( reuters ) - transgender people wi...,1
2,senior u . s . republican senator : 'let mr . ...,washington ( reuters ) - the special counsel i...,1
3,fbi russia probe helped by australian diplomat...,washington ( reuters ) - trump campaign advise...,1
4,trump wants postal service to charge 'much mor...,seattle / washington ( reuters ) - president d...,1
...,...,...,...
44893,mcpain : john mccain furious that iran treated...,21 st century wire says as 21 wire reported ea...,0
44894,justice ? yahoo settles e - mail privacy class...,21 st century wire says it s a familiar theme ...,0
44895,sunnistan : us and allied ‘ safe zone ’ plan t...,patrick henningsen 21 st century wireremember ...,0
44896,how to blow $ 700 million : al jazeera america...,21 st century wire says al jazeera america wil...,0
44897,10 u . s . navy sailors held by iranian milita...,21 st century wire says as 21 wire predicted i...,0

In [41]:
# in order to make sure attributes other than text and title can be taken systematically, I put the other attributes ahead of title and text
df_all = df_date.merge(right = df_all,how = 'inner', left_index=True, right_index=True)
df_all

,year,month,day,weekday,aprilfool_close,aprilfool_no,aprilfool_not sure,aprilfool_yes,title,text,label
0,2017,12,31,6,0,1,0,0,"as u . s . budget fight looms , republicans fl...",washington ( reuters ) - the head of a conserv...,1
1,2017,12,29,4,0,1,0,0,u . s . military to accept transgender recruit...,washington ( reuters ) - transgender people wi...,1
2,2017,12,31,6,0,1,0,0,senior u . s . republican senator : 'let mr . ...,washington ( reuters ) - the special counsel i...,1
3,2017,12,30,5,0,1,0,0,fbi russia probe helped by australian diplomat...,washington ( reuters ) - trump campaign advise...,1
4,2017,12,29,4,0,1,0,0,trump wants postal service to charge 'much mor...,seattle / washington ( reuters ) - president d...,1
...,...,...,...,...,...,...,...,...,...,...,...
44893,2016,1,16,5,0,1,0,0,mcpain : john mccain furious that iran treated...,21 st century wire says as 21 wire reported ea...,0
44894,2016,1,16,5,0,1,0,0,justice ? yahoo settles e - mail privacy class...,21 st century wire says it s a familiar theme ...,0
44895,2016,1,15,4,0,1,0,0,sunnistan : us and allied ‘ safe zone ’ plan t...,patrick henningsen 21 st century wireremember ...,0
44896,2016,1,14,3,0,1,0,0,how to blow $ 700 million : al jazeera america...,21 st century wire says al jazeera america wil...,0
44897,2016,1,12,1,0,1,0,0,10 u . s . navy sailors held by iranian milita...,21 st century wire says as 21 wire predicted i...,0

In [42]:
df_all = df_subject.merge(right = df_all,how = 'inner', left_index=True, right_index=True)
df_all

,subject_Government News,subject_Middle-east,subject_News,subject_US_News,subject_left-news,subject_politics,subject_politicsNews,subject_worldnews,year,month,day,weekday,aprilfool_close,aprilfool_no,aprilfool_not sure,aprilfool_yes,title,text,label
0,0,0,0,0,0,0,1,0,2017,12,31,6,0,1,0,0,"as u . s . budget fight looms , republicans fl...",washington ( reuters ) - the head of a conserv...,1
1,0,0,0,0,0,0,1,0,2017,12,29,4,0,1,0,0,u . s . military to accept transgender recruit...,washington ( reuters ) - transgender people wi...,1
2,0,0,0,0,0,0,1,0,2017,12,31,6,0,1,0,0,senior u . s . republican senator : 'let mr . ...,washington ( reuters ) - the special counsel i...,1
3,0,0,0,0,0,0,1,0,2017,12,30,5,0,1,0,0,fbi russia probe helped by australian diplomat...,washington ( reuters ) - trump campaign advise...,1
4,0,0,0,0,0,0,1,0,2017,12,29,4,0,1,0,0,trump wants postal service to charge 'much mor...,seattle / washington ( reuters ) - president d...,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44893,0,1,0,0,0,0,0,0,2016,1,16,5,0,1,0,0,mcpain : john mccain furious that iran treated...,21 st century wire says as 21 wire reported ea...,0
44894,0,1,0,0,0,0,0,0,2016,1,16,5,0,1,0,0,justice ? yahoo settles e - mail privacy class...,21 st century wire says it s a familiar theme ...,0
44895,0,1,0,0,0,0,0,0,2016,1,15,4,0,1,0,0,sunnistan : us and allied ‘ safe zone ’ plan t...,patrick henningsen 21 st century wireremember ...,0
44896,0,1,0,0,0,0,0,0,2016,1,14,3,0,1,0,0,how to blow $ 700 million : al jazeera america...,21 st century wire says al jazeera america wil...,0
44897,0,1,0,0,0,0,0,0,2016,1,12,1,0,1,0,0,10 u . s . navy sailors held by iranian milita...,21 st century wire says as 21 wire predicted i...,0

In [43]:
# mix the order of dataframe, in order to make sure the order of label are mixed
df_all = df_all.sample(frac=1, replace=True, random_state=1)

In [44]:
df_all['label']

33003    0
12172    1
5192     1
32511    0
43723    0
        ..
11419    1
36294    0
31438    0
32646    0
33429    0
Name: label, Length: 44898, dtype: int64

In [45]:
# reset index
df_all = df_all.reset_index()
df_all = df_all.drop(columns=['index'])

In [46]:
df_all

,subject_Government News,subject_Middle-east,subject_News,subject_US_News,subject_left-news,subject_politics,subject_politicsNews,subject_worldnews,year,month,day,weekday,aprilfool_close,aprilfool_no,aprilfool_not sure,aprilfool_yes,title,text,label
0,0,0,0,0,0,1,0,0,2017,2,24,4,0,1,0,0,standing ovation ! nigel farage trolls cnn dur...,. @ nigel _ farage tells the # cpac 2017 crowd...,0
1,0,0,0,0,0,0,0,1,2017,12,15,4,0,1,0,0,'congratulations' : eu moves to brexit phase t...,brussels ( reuters ) - the european union agre...,1
2,0,0,0,0,0,0,1,0,2017,3,2,3,0,1,0,0,white house aides told to preserve materials i...,washington ( reuters ) - the white house couns...,1
3,0,0,0,0,0,1,0,0,2017,4,20,3,0,1,0,0,democrats sell promo t - shirt : “ democrats g...,"yes , the democrats think it s a good thing to...",0
4,0,0,0,1,0,0,0,0,2016,12,25,6,0,1,0,0,this year : let ’ s make christmas great again …,"this year , let s try something a little diffe...",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44893,0,0,0,0,0,0,0,1,2017,12,25,0,0,1,0,0,driver rams german party headquarters in appar...,berlin ( reuters ) - a man drove a car at the ...,1
44894,0,0,0,0,0,1,0,0,2015,11,27,4,0,1,0,0,chicago thugs watched 9 yr old play on swings ...,update : no # blacklivesmatter protests planne...,0
44895,0,0,0,0,0,1,0,0,2017,8,28,0,0,1,0,0,one beer company praised for shutting down bus...,the anheuser - busch brewery put beer producti...,0
44896,0,0,0,0,0,1,0,0,2017,4,2,6,1,0,0,0,republican turns tables on fbi : deputy direct...,gchq director robert hannigan is stepping down...,0
44897,0,0,0,0,0,1,0,0,2017,1,2,0,0,1,0,0,pelosi lied about “ affordable ” healthcare an...,via : wt,0

In [47]:
save_path='.\DataSet\preprocessed_data.csv'
df_all.to_csv(save_path, sep='|', index=False)

In [48]:
df_all = pd.read_csv(save_path,sep='|')
df_all

,subject_Government News,subject_Middle-east,subject_News,subject_US_News,subject_left-news,subject_politics,subject_politicsNews,subject_worldnews,year,month,day,weekday,aprilfool_close,aprilfool_no,aprilfool_not sure,aprilfool_yes,title,text,label
0,0,0,0,0,0,1,0,0,2017,2,24,4,0,1,0,0,standing ovation ! nigel farage trolls cnn dur...,. @ nigel _ farage tells the # cpac 2017 crowd...,0
1,0,0,0,0,0,0,0,1,2017,12,15,4,0,1,0,0,'congratulations' : eu moves to brexit phase t...,brussels ( reuters ) - the european union agre...,1
2,0,0,0,0,0,0,1,0,2017,3,2,3,0,1,0,0,white house aides told to preserve materials i...,washington ( reuters ) - the white house couns...,1
3,0,0,0,0,0,1,0,0,2017,4,20,3,0,1,0,0,democrats sell promo t - shirt : “ democrats g...,"yes , the democrats think it s a good thing to...",0
4,0,0,0,1,0,0,0,0,2016,12,25,6,0,1,0,0,this year : let ’ s make christmas great again …,"this year , let s try something a little diffe...",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44893,0,0,0,0,0,0,0,1,2017,12,25,0,0,1,0,0,driver rams german party headquarters in appar...,berlin ( reuters ) - a man drove a car at the ...,1
44894,0,0,0,0,0,1,0,0,2015,11,27,4,0,1,0,0,chicago thugs watched 9 yr old play on swings ...,update : no # blacklivesmatter protests planne...,0
44895,0,0,0,0,0,1,0,0,2017,8,28,0,0,1,0,0,one beer company praised for shutting down bus...,the anheuser - busch brewery put beer producti...,0
44896,0,0,0,0,0,1,0,0,2017,4,2,6,1,0,0,0,republican turns tables on fbi : deputy direct...,gchq director robert hannigan is stepping down...,0
44897,0,0,0,0,0,1,0,0,2017,1,2,0,0,1,0,0,pelosi lied about “ affordable ” healthcare an...,via : wt,0

# 6. Interception for Train and Test Set

In [49]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(df_all, test_size=0.2)

In [50]:
train['label']

1133     0
19449    1
23580    0
13321    0
18349    1
        ..
28815    0
10128    1
9684     0
38329    1
13228    0
Name: label, Length: 35918, dtype: int64

In [51]:
test['label']

33743    1
14939    0
194      0
33014    0
3249     1
        ..
18440    0
2679     1
26072    1
17671    1
6361     1
Name: label, Length: 8980, dtype: int64

In [52]:
train.to_csv('.\DataSet\Train.csv', sep='|', index=False)
test.to_csv('.\DataSet\Test.csv', sep='|', index=False)